echo '<svg fill="none" xmlns="http://www.w3.org/2000/svg">
    <foreignObject width="100%" height="100%">
        <div xmlns="http://www.w3.org/1999/xhtml">' > embed.svg

cat index.html >> embed.svg

echo '
        </div>
    </foreignObject>
</svg>' >> embed.svg
